 const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_START : " GOOGLE_SIGN_START",
    SIGN_SUCCESS : "SIGN_SUCCESS ",
    SIGN_FAIL : "SIGN_FAIL",
    EMAIL_SIGN_START : " EMAIL_SIGN_START",
    CHECK_USER_SESSION : "CHECK_USER_SESSION",
    SIGN_OUT_START : "SIGN_OUT_START",
    SIGN_OUT_SUCCESS : "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAIL : "SIGN_OUT_FAIL",
    SIGN_UP_START : "SIGN_UP_START",
    SIGN_UP_SUCCESS : "SIGN_UP_SUCCESS",
    SIGN_UP_FAIL : "SIGN_UP_FAIL"
    
  };
  export default UserActionTypes;